### PR TITLE
Add citation file for PyMeasure repository

### PR DESCRIPTION
**Pull request by mcdo0486**
Hi,

I'm collaborating on a paper that uses PyMeasure and I would like to cite this main repository in the paper. Popular open source projects often include a preference for how the project is cited and I think that can be useful for PyMeasure.

Specifically, because the PyMeasure framework is in active development with many changes to the codebase, I'd like the citation to include as much info into the version of PyMeasure that was used at time of publication. That will help make sure any shared code that builds off of PyMeasure at the time of the publication release will work.

GitHub [supports](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) using the [Citation File Format](https://github.com/citation-file-format/citation-file-format/tree/main) to integrate citation information into the GitHub repo. You can see what that looks like in the branch for this PR here: https://github.com/mcdo0486/pymeasure/tree/dev/citation (look at the "Cite this repository" on the right)

The [CITATION.cff](https://github.com/mcdo0486/pymeasure/blob/dev/citation/CITATION.cff) I'm proposing keeps things simple. It includes a generic message to encourage citing PyMeasure, credits "PyMeasure Developers" like the license, includes the current release version, and the commit of that release. This would add another step to the action list of publishing a version of PyMeasure as the release version and commit would need to be updated in CITATION.cff.

Including the CITATION.cff will encourage people to cite PyMeasure and will help capture info about the version of PyMeasure that was used at the time of publication.

Here are some examples of how PyMeasure has been cited so far, from a quick search of PyMeasure in google scholar.

https://doi.org/10.1063/5.0032116 
`8. See https://pymeasure.readthedocs.io for PyMeasure, Scientific package.`

https://doi.org/10.1016/j.cpc.2018.07.024
`11. PyMeasure scientific package, URL https://pymeasure.readthedocs.io/`

https://orbi.umons.ac.be/bitstream/20.500.12907/42331/1/R-testbench__v_1.0.pdf
`[24]. PyMeasure Developers, PyMeasure scientific package
— PyMeasure 0.8.0 documentation, 2020
(https://pymeasure.readthedocs.io/en/latest/index.html). `

https://doi.org/10.3390/software2010005
`35. Jermain, C.; Minhhai; Rowlands, G.; Girard, H.-L.; Schippers, C.; Schneider, M.; Chweiser; Buchner, C.; Spirito, D.; Feinstein, B.; et al. Ralph-Group/Pymeasure: PyMeasure 0.8; Zenodo; Organisation Europenne Pour la Recherche Nucleaire: Geneva, Switzerland, 2020.`

### CODE REVIEW

**Comment by mcdo0486** [comment]
The point of the CITATION.cff is to provide guidance in how the project should be cited right in the github repo. It can include a DOI entry, that is part of the CFF file format. It would have to be updated manually after a release to reflect the updated version, but I don't think that will be much of a task, I'm happy to the file up to date with each PIP release.

This can be a good time to register a new DOI through zenodo that points to the correct repository, if it has been four years since the last one was updated. It would be an opportunity to update some metadata, like using "Pymeasure Developers" for the authors like the existing license file.

**Comment by BenediktBurger** [comment]
In that other issue I asked Colin (not that active) to update Zenodo regardin pymeasure.

If it could link to the _permanent_ Zenodo DOI, it would be great, because that way you always get the most recent entry.

**Comment by mcdo0486** [comment]
I can add the DOI that links to all versions of PyMeasure to the CITATION.cff. The version number in the CITATION.cff file would still need to be incremented to clearly show what version was used at time of citing, but it can link to the Zenodo with all versions. If someone will be downloading the release zip from Zenodo to install PyMeasure, they'll know what version to download.

It could be a while for a resolution on Zenodo DOI if it has been many years since it was updated. This CITATION.cff could be added as is, and when the existing Zenodo DOI metadata/release info gets updated I can add that DOI. Or if a new Zenodo DOI is registered.

**Comment by BenediktBurger** [comment]
Use the current Zenodo DOI, once we have a new one, we can adjust it.

**Comment by mcdo0486** [comment]
> Use the current Zenodo DOI, once we have a new one, we can adjust it.

Ok, that has been pushed up

**Comment by BenediktBurger** [comment]
An additional idea: could there be a workflow run (maybe "on release"), which modifies the version in that file?

**Comment by BenediktBurger** [comment]
This article describes some ideas on how to cite software: https://zenodo.org/records/3479199

I suggest: PyMeasure Developers, PyMeasure v.X.Y.Z, Zenodo, Zenodo DOI...

Similar to:
Cruz, K. et al. (2014), “Eudoxus”, v1.0, Zenodo, doi.10.5281/zenodo.12345

**Comment by mcdo0486** [comment]
The CITATION.cff has been updated to use the `doi` key directory instead of using `identifiers`. This adds the DOI to the citation for the automatically generated APA and Bibtex styles. 

APA:
`PyMeasure Developers. PyMeasure (Version 0.13.1) [Computer software]. https://doi.org/10.5281/zenodo.595633`

Bibtex:
```
@software{PyMeasure_Developers_PyMeasure,
author = {{PyMeasure Developers}},
doi = {10.5281/zenodo.595633},
title = {{PyMeasure}},
url = {https://github.com/pymeasure/pymeasure},
version = {0.13.1}
}
```

The auto-generated citation styles are close to the citation style example you gave, but not exact, there are plenty of citation styles out there.

It is possible to have a github workflow commit changes to the repository. There could be a step to parse CHANGES.rst to grab the latest version and replace that in the CITATION.cff. However that adds complexity. I think if we created a actions release workflow that automates some of the steps in RELEASE.md then it would be worth revisiting. There was an official [`actions/create-release`](https://github.com/actions/create-release) but that isn't maintained anymore, instead it points to some community actions that automate the creation of a GitHub release.

**Comment by mcdo0486** [comment]
I was thinking about updating CITATION.cff before the release to make sure the updated version was in the release.

You referred to using the github action "release" event trigger and that would work as well for updating the CITATION.cff after a release. Looking up that event trigger, there is the GITHUB_REF env var that is the release's tag. The "version: #" line in the CITATION file could be replaced with the tag, which would be much more reliable than parsing CHANGES.rst.

**Comment by BenediktBurger** [comment]
> I was thinking about updating CITATION.cff before the release to make sure the updated version was in the release.
> 
> You referred to using the github action "release" event trigger and that would work as well for updating the CITATION.cff after a release. Looking up that event trigger, there is the GITHUB_REF env var that is the release's tag. The "version: #" line in the CITATION file could be replaced with the tag, which would be much more reliable than parsing CHANGES.rst.

That is what I thought about.

> The auto-generated citation styles are close to the citation style example you gave, but not exact, there are plenty of citation styles out there.

I liked the idea, to mention _Zenodo_ as the publisher. Is that possible?

Thanks for all your work!

**Comment by mcdo0486** [comment]
I tried a bunch of configurations, and seems the ruby-cff parser doesn't include the publisher in the auto-generated citation for software types of work. I've included the publisher in the CITATION.cff anyways if people want to include it in their style of citation.

**Comment by BenediktBurger** [comment]
Thanks for adding this file.

We have to see, why CI fails.

**Comment by CasperSchippers** [comment]
Yes, I'm fine with the citation style (though I do not have a strong opinion on this, since I think many people will also disregard the  provided citation in favour of the style they use themselves).

**Comment by BenediktBurger** [comment]
One last request @mcdo0486 :
Could you adjust the `RELEASE.md`, please?
Probably around points 3 or 4 the version in citation.dff should be adjusted.

**Comment by bilderbuchi** [comment]
Yes, I'm fine with adding a citation file, thanks for pinging me. :-)
It's a bit annoying that the version has to be updated manually, since we spent some effort to single-source the version string, but it's not a big deal. 🤷 Please do add a step to Release.md, though.

**Comment by BenediktBurger** [comment]
If you merge master, the CI checks should succeed again.

**Comment by mcdo0486** [comment]
Added a step to RELEASE.md, thanks for the comments and review. I think this change will encourage the inclusion of a version number when citing PyMeasure's active code base.

**Comment by msmttchr** [comment]
> @bilderbuchi , @msmttchr , @CasperSchippers , are you fine with that citation style?

Ok for me.

**Pull request merged**
