### PR TITLE
Fix file access issue

### PR DESCRIPTION
**Pull request by CasperSchippers**
PR to solve the issue raised in #235.

### CODE REVIEW

**Comment by CasperSchippers** [comment]
I proposed a test and a fix for this issue. Could (one of) you have a look at these, @bilderbuchi  @cjermain?

Interestingly, with this test, it seemed to show that the issue arises only on windows. I am not sure if that is actually the case or if the test isn't adequate on Linux and mac.

**Comment by msmttchr** [comment]
@CasperSchippers , I have tried your fix with Windows and it works fine for me. I believe that the issue is not visible in Linux since this OS use a different file locking mechanism compared to Windows (https://en.wikipedia.org/wiki/File_locking).

**Comment by CasperSchippers** [comment]
It seems you're right about the locking mechanism.

**Comment by msmttchr** [comment]
> It seems you're right about the locking mechanism.

Are you going to merge your PR ?

**Comment by bilderbuchi** [comment]
@msmttchr Casper requested a review/another set of eyes to check this PR before merging.. :-)
In any case, looks good to me. Thanks for adding a test for the issue, too!

**Pull request merged**
