### PR TITLE
Add save functionality to sequencer

### PR DESCRIPTION
**Pull request by mcdo0486**
Added functionality to serialize the sequence tree for saving.

Added a save button and moved "Load Sequence" and "Save Sequence" above the QTreeWidget

### CODE REVIEW

**Comment by bmoneke** [comment]
Hey @mcdo0486,
Thanks für your suggestions.

Is it feasible to divide the Pr in two? It seems, that the first part does not need the SequenceDialog, such that the dialog could follow after.
Reducing the scope of a PR makes it much easier to handle. It reduces the complexity and the amount of time in one go to look it all through.

**Comment by mcdo0486** [comment]
> Hey @mcdo0486, Thanks für your suggestions.
> 
> Is it feasible to divide the Pr in two? It seems, that the first part does not need the SequenceDialog, such that the dialog could follow after. Reducing the scope of a PR makes it much easier to handle. It reduces the complexity and the amount of time in one go to look it all through.

Ok, I've removed `SequenceDialog` and edited the merge request description

**Comment by msmttchr** [comment]
@mcdo0486, actually I have started long time ago a PR #518 and included some provision for saving the sequencer data.
I recently updated it to align to latest master and for me it should be functional, but could You please have a try and comment whether we can include the save functionality in that PR or you prefer to bring forward this PR ?

**Comment by mcdo0486** [comment]
> @mcdo0486, actually I have started long time ago a PR #518 and included some provision for saving the sequencer data. I recently updated it to align to latest master and for me it should be functional, but could You please have a try and comment whether we can include the save functionality in that PR or you prefer to bring forward this PR ?

Gotcha. That PR does a lot more than add save functionality, it is a major refactor of the sequencer widget moving away from QTreeWidget and breaking out the logic to make it compatible with a draft PR for console mode. That is a much larger scope for the PR.

That said, I'd be cool with working on a refactor of the sequencer. I've setup the users that wanted the functionality with my fork so there isn't a rush for anything to be merged into pymeasure master.

**Comment by mcdo0486** [comment]
Moved development to PR https://github.com/pymeasure/pymeasure/pull/518

**Pull request closed without merging**
