### PR TITLE
Fix for warning by pyvisa on using deprecated API (get_instrument)

### PR DESCRIPTION
**Pull request by msmttchr**
Minor fix on pyvisa deprecated API

### CODE REVIEW

**Review by CasperSchippers — APPROVED** [review]
Thanks for this fix. 

Could you add yourself to the authors lists at AUTHORS.txt and docs/about/authors.rst.

**Comment by bilderbuchi** [comment]
LGTM. I am wondering why we don't see the FutureWarning in our pytest runs, though? How did you become aware of the deprecation, @msmttchr ?

**Comment by bilderbuchi** [comment]
> I am wondering why we don't see the FutureWarning in our pytest runs, though.

Oh I see, we don't cover that part of the code, yet - see #362

**Comment by msmttchr** [comment]
> LGTM. I am wondering why we don't see the [FutureWarning](https://github.com/pyvisa/pyvisa/blob/master/pyvisa/highlevel.py#L3352) in our pytest runs, though. Is there a way to surface these warnings in CI? It's not the first pyvisa deprecation we address.
> How did you become aware of the deprecation, @msmttchr ?

I just used the module in my setup and the warning is shown in the DOS box.
I thought this could be related also to the version of pyvisa people are using.

**Comment by bilderbuchi** [comment]
Yes it is related, I confirmed that the change is fine with out supported range of pyvisa versions.

**Pull request merged**
