### PR TITLE
Fix a couple of typos in procedure.rst

### PR DESCRIPTION
**Pull request by kpet**

### CODE REVIEW

**Comment by BenediktBurger** [comment]
Hey @kpet , thanks for your contribution.

Please add yourself to the authors.txt file, unless you do not wish so.

If you do not know, how to do it, I'll be glad to assist.

**Comment by kpet** [comment]
It feels like too much credit for fixing a couple of typos :). I'll gladly add myself as and when I make a more meaningful contribution. I've just read the excellent tutorials and I'm eager to start playing with PyMeasure. If it works well for me, I'll likely end up contributing a couple of instruments. Thanks for looking after this great project!

**Comment by BenediktBurger** [comment]
Thanks for your words.

So I merge it, as is?

**Comment by kpet** [comment]
Works for me, thanks.

**Comment by BenediktBurger** [comment]
Thanks for your work!

**Pull request merged**
