### PR TITLE
Link Keysight, Agilent, and HP documentation pages.

### LINKED ISSUE #1020: Connect HP, Agilent, and Keysight in documentation
In the documentation these three brands should be connected like Teledyne and LeCroy.

That way it is easier to see similarities or find a suitable driver.

### PR DESCRIPTION
**Pull request by BenediktBurger**
closes #1020

### CODE REVIEW

**Comment by BenediktBurger** [comment]
Could anyone look at this tiny (6 liner and almost obvious) PR, please? @msmttchr , @CasperSchippers , @bilderbuchi

**Comment by CasperSchippers** [comment]
I'll have a look tonight!

**Comment by LongnoseRob** [comment]
LGTM, thanks for the enhancement.

**Comment by bilderbuchi** [comment]
:shipit:

**Comment by BenediktBurger** [comment]
Thanks for the reviews

**Pull request merged**
