### PR TITLE
contribute.rst for GitHub Desktop users

### PR DESCRIPTION
**Pull request by OrionSmedley**

### CODE REVIEW

**Comment by OrionSmedley** [comment]
Closes  #1170

**Comment by BenediktBurger** [comment]
> Closes #1170

You have to state this in the opening post (can be added via an edit).
I just made it manually on the right side ("Development")

**Comment by BenediktBurger** [comment]
Thanks for the suggestion.
It looks good.

If you want to, you can add yourself to the authors.txt.
If not, I'll merge this as is.

**Comment by OrionSmedley** [comment]
Oh, thank you!
Just added that.

**Pull request merged**
