### PR TITLE
Fix checkboxes not working for groups in inputs-widget

### PR DESCRIPTION
**Pull request by CasperSchippers**
I came across an issue that prevented the input-groups from working correctly when they were controlled by a checkbox. This issue only appears when using PyQt6 and PySide6. In this PR this is fixed by changing from the stateChanged to the toggled signal.

### CODE REVIEW

**Comment by bilderbuchi** [comment]
Is ot feasible to add a test for the breaking behaviour, which then shows that it's fixed by the implemented change?

**Comment by bmoneke** [comment]
Good idea to expand the tests.
There is a pyqt pytest plug in.
However, some more complex workings are different to test.

**Comment by CasperSchippers** [comment]
That's indeed a good idea. I've had some time to find out how pytest-qt works and implemented some tests.

**Review by msmttchr — APPROVED** [review]
OK for me.

**Comment by bilderbuchi** [comment]
@CasperSchippers do you want to merge this?

**Comment by CasperSchippers** [comment]
Ah, right, yes; I'll merge this

**Pull request merged**
