### PR TITLE
Bump codecov action version.

### PR DESCRIPTION
**Pull request by BenediktBurger**
Maybe version 4 is a fix for #1090

### CODE REVIEW

**Comment by driftregion** [comment]
Here is a purportedly successful bump in codecov version from 3 to 4:
https://github.com/Open-Attestation/document-store/pull/170/files

(linked from https://github.com/codecov/codecov-action/issues/1292)

**Comment by BenediktBurger** [comment]
> Here is a purportedly successful bump in codecov version from 3 to 4: https://github.com/Open-Attestation/document-store/pull/170/files
> 
> (linked from [codecov/codecov-action#1292](https://github.com/codecov/codecov-action/issues/1292))

Thanks for making me aware of that. Unfortunately, they have another issue with a workflow calling another one, but both are in the main repo.

Our problem is, that work flows in forks cannot access the secret token.

**Comment by driftregion** [comment]
It seems the established solution is to use `pull_request_target`. Example: https://github.com/hyperledger/firefly-tezosconnect/pull/20

See also:
https://github.com/codecov/codecov-action/issues/29 

This solution seems to be unviable if there is potential for abuse of the codecov token or other secrets. I haven't yet found anything on whether or not it's possible to isolate secrets to a particular workflow.

**Comment by BenediktBurger** [comment]
As this PR is from a fork, the upload will fail, such that it cannot be tested.

**Pull request closed without merging**
