### PR TITLE
Fix VISAAdapter flush_read_buffer

### PR DESCRIPTION
**Pull request by ileu**
Added `discard_receive_buffer` after `discard_read_buffer` to make sure buffer is empty.

See discussion #965.

### CODE REVIEW

**Comment by bmoneke** [comment]
Thanks for the PR.

You may add yourself to the authors.txt, if you like.

Could you please try the modified flush method with a serial connection (ASRL/COM), to make sure, that it does not raise any error.

**Comment by ileu** [comment]
Seems to work fine with a serial connection.

I verified with the following code:
```
adapter = VISAAdapter("ASRL5::INSTR")

print(adapter.read_bytes(-1))

adapter.write("ver")

time.sleep(0.5)

adapter.flush_read_buffer()

print(adapter.read_bytes(-1))

adapter.close()
```

resulting in the following 

```
b''
b''
```
and without the `adapter.flush_read_buffer()`

```
b''
b'ver\r\nattocube ANC300 controller version 1.2.2-3 2019-01-25 11:02\r\nANC150 compatibillity console\r\nOK\r\n> '
```

**Comment by bmoneke** [comment]
Thank you for your PR.

**Comment by bilderbuchi** [comment]
@bmoneke do we also need to adapt the ProtocolAdapter's `flush_read_buffer` ? It contains a copy of the code in the VISAAdapter.

**Comment by bmoneke** [comment]
Thanks for remembering that part.

You're right, that it does not mirror the visa adapter anymore. On the other hand, it's there for checking, whether it is called. In this case, it is easier, if "flush" is called once for every "flush read buffer".

Let's keep as is.

**Pull request merged**
