### PR TITLE
v0.9 release

### PR DESCRIPTION
**Pull request by cjermain**
This PR bumps the version number for the 0.9 release. It also compiles the changes over the release.

### CODE REVIEW

**Comment by bilderbuchi** [comment]
can we also get #384 in? I think this now only needs a once-over by you, Colin.

**Comment by bilderbuchi** [comment]
LGTM, thank you! Will you also bump the pymeasure conda package at the same time? https://github.com/conda-forge/pymeasure-feedstock

**Comment by cjermain** [comment]
I added a bunch of commits above after reviewing the Flake8 linting.

**Comment by cjermain** [comment]
@bilderbuchi, I will bump the conda-forge version right after the main release. I will add you as a maintainer at the same time.

**Comment by bilderbuchi** [comment]
I'm actually a bit surprised that the flake8 linting output is not "noisy" at all. Maybe it's time to pull that into CI more prominently (#346). We'll have to check if there is a good problem matcher for flake8 by now, that would be useful to make errors more prominent in the PR diff view.

**Comment by bilderbuchi** [comment]
:partying_face: :champagne:

**Pull request merged**
