### PR TITLE
Deprecation warning texts improved

### PR DESCRIPTION
**Pull request by bmoneke**
The adapters' deprecation warnings did not mention, what is deprecated. I fixed it.
See #672

### CODE REVIEW

**Review by CasperSchippers — COMMENTED** [review]
That is indeed an improvement of the deprecation warnings. I was wondering if it would be possible to also add when these features will be removed?

**Comment by bmoneke** [comment]
We have not yet determined, when they will be removed (at the latest before 1.0, I think)

**Review by CasperSchippers — APPROVED** [review]
Fair enough, if that is to be for a later update, I approve.

**Comment by bilderbuchi** [comment]
Indeed, we don't have a formal deprecation schedule, yet. 

Thank you, LGTM.

**Pull request merged**
