### PR TITLE
Fixes for Agilent B1500 instrument

### PR DESCRIPTION
**Pull request by moritzj29**
Hi,

these are two fixes for the Agilent B1500 instrument:

- fixing the ability to select fixed measurement ranges (negative indizes), addressing #366 
- (code cleanup and restructuring of ranging classes)
- fixing FMT11 formatting

### CODE REVIEW

**Comment by bilderbuchi** [comment]
Thank you for the super-quick fix! 
Sadly, there is no way of checking the fixes without that device, or even realistically reviewing what is going on in this seemingly quite complicated instrument. I don't particularly like that, but I'll merge this right now. To mitigate the situation, I ask you and @HansMalo to do thorough testing of as much of the functionality as feasible when you get the opportunity.

**Comment by HansMalo** [comment]
Hello, 
 many thanks for the fast reply. I think I can test it today.

**Comment by HansMalo** [comment]
Hello again, 
 i tried the sampling setup and found it not working directly. With the given setting (MM 10, SMUs) the B1500 will return the data after the measurement and will not provide any data while it is busy.
So I changed the code passage for excecuting the measurement and retrieving data. @moritzj29 Would you be so kind and give this a review so i could be implemented [here ](https://pymeasure.readthedocs.io/en/latest/api/instruments/agilent/agilentB1500.html#sampling-measurement-with-4-smus) ?

```
# choose measurement mode
b1500.meas_mode('SAMPLING', *b1500.smu_references) #order in smu_references determines order of measurement
# *b1500.smu_references includes all smus, to specify single smu use "b1500.smux" with x the smu number
number_of_channels = len(b1500.smu_references)

# settings for individual SMUs
# *b1500.smu_references includes all smus, to specify single smu use "b1500.smux" with x the smu number
for smu in b1500.smu_references:
    smu.enable() #enable SMU
    smu.adc_type = 'HSADC' #set ADC to high-speed ADC
    smu.meas_range_current = '1 nA'
    smu.meas_op_mode = 'COMPLIANCE_SIDE' # other choices: Current, Voltage, FORCE_SIDE, COMPLIANCE_AND_FORCE_SIDE

b1500.sampling_mode = 'LINEAR'
# b1500.adc_averaging = 1
# b1500.adc_auto_zero = True
b1500.adc_setup('HSADC','AUTO',1)
#b1500.adc_setup('HSADC','PLC',1)
nop=11
b1500.sampling_timing(2,0.005,nop) #MT: bias hold time, sampling interval, number of points
b1500.sampling_auto_abort(False,post='BIAS') #MSC: BASE/BIAS
b1500.time_stamp = True

# Sources
b1500.smu1.sampling_source('VOLTAGE','Auto Ranging',0,1,0.001) #MV/MI: type, range, base, bias, compliance
b1500.smu2.sampling_source('VOLTAGE','Auto Ranging',0,1,0.001)
b1500.smu3.ramp_source('VOLTAGE','Auto Ranging',-1,stepsize=0.1,pause=20e-3) #output starts immediately! (compared to sweeps)
b1500.smu4.ramp_source('VOLTAGE','Auto Ranging',-1,stepsize=0.1,pause=20e-3)

#Start Measurement
b1500.check_errors()
b1500.clear_buffer()
b1500.clear_timer()
b1500.send_trigger()

# read measurement data all at once
b1500.check_idle() #wait until measurement is finished
data = b1500.read_data(nop)

#sweep constant sources back to 0V
b1500.smu3.ramp_source('VOLTAGE','Auto Ranging',0,stepsize=0.1,pause=20e-3)
b1500.smu4.ramp_source('VOLTAGE','Auto Ranging',0,stepsize=0.1,pause=20e-3)
```

**Comment by moritzj29** [comment]
Hello @HansMalo,

if I understand correctly, you added this to the example code:

```
#Start Measurement
b1500.check_errors()
b1500.clear_buffer()
b1500.clear_timer()
b1500.send_trigger()

# read measurement data all at once
b1500.check_idle() #wait until measurement is finished
data = b1500.read_data(nop)
```

The first block is definitely missing in the sampling example! No trigger, no data... I will add this to the documentation.

The second block depends on how you want your data to be read. This is more clearly stated in the IV measurement example. There are 2 possibilities:

1. read data after measurement -> this is done by your second block
2. read data after each point -> this done by the for loop in the example using `b1500.read_channels()`

So in your code you do not have live plotting I assume.
For the `read_channels()` method you have to configure your data format correctly, since you need to know how many values are returned for one measurement point. This may change with chosen data format, please have a look in the "Programming Guide" for that, I don't recall every detail... 

With the format 21 specified in the example (`b1500.data_format(21, mode=1)`), I use the given methods for live plotting. Maybe I missed another line while transferring it to the example code for the docs. I will check on this next week. (and the overall example code)

It's a great help to finally have someone cross-checking the code! If you have any questions I'll try my best to help out!

**Comment by HansMalo** [comment]
Hello @moritzj29 , 
 I did not know of the possiblity of live data readout yet, thank you for the hint.
I tested your fixed b1500a.py and it sends the correct command, when setting xxA fixed range.

The live readout also works. 

A minor thing that I did not properly found the reason: sometimes FMT can be set to a value the driver does not yet allow when initializing the instrument. For now the program stops working. for example the line
```
b1500=AgilentB1500("GPIB0::17::INSTR", read_termination='\r\n', write_termination='\r\n', timeout=600000)
```
stops the program if a previous application set FMT 13 (in my case). Since FMT is set anyway somewhere in the code after initialization, does it make sense to stop the script if FMT is not supported at initialization of the script? From my point of view the FMT set later anyway. With the script stopping at initialization the only way to fix this is to manually send a GPIB command with a proper FMT 21 or something like that. Maybe a warning is enough.

many thanks for the fast fix. 
I will not have access to the instrument next 2month, but a colleague appreciates pretty much what you are doing.

**Pull request merged**
