### PR TITLE
Fix issues #583

### PR DESCRIPTION
**Pull request by msmttchr**
Another option is to remove SwissArmyFake from documentation, but I am not sure whether it is better or nor.

### CODE REVIEW

**Comment by msmttchr** [comment]
@samcondon4, could You please have a look and comment on the change ?

**Comment by bilderbuchi** [comment]
Erm, I'm currently in the process of fixing this in #584? (actually have, now)

**Comment by bilderbuchi** [comment]
> Another option is to remove SwissArmyFake from documentation, but I am not sure whether it is better or nor.

This fixes the current error, yes, but similarly malformed autodoc statements (for stuff that should be documented) would still slip through.

**Comment by msmttchr** [comment]
> Erm, I'm currently in the process of fixing this in #584? (actually have, now)

Closing it then, easy  :)

**Comment by msmttchr** [comment]
Addressed by #584

**Pull request closed without merging**
