### PR TITLE
Change CI from conda to mamba.

### PR DESCRIPTION
**Pull request by bmoneke**
One piece of #348 
For faster tests.

Inspired by https://github.com/pymeasure/pyleco/pull/7

### CODE REVIEW

**Comment by bmoneke** [comment]
Wow, the first test finished after 1 minute and the last one after 6 minutes.

I'd say that's quite an improvement over conda.

**Comment by bilderbuchi** [comment]
Indeed! conda is really slow...
There's some build warning: https://github.com/pymeasure/pymeasure/actions/runs/5551780213/jobs/10138293480?pr=947#step:3:1

**Comment by bmoneke** [comment]
Thank you for looking at these details.

I guess it affects also pyleco.

**Comment by bmoneke** [comment]
> Indeed! conda is really slow... There's some build warning: https://github.com/pymeasure/pymeasure/actions/runs/5551780213/jobs/10138293480?pr=947#step:3:1

I fixed the warnings

**Comment by bilderbuchi** [comment]
Awesome, LGTM!

**Comment by bmoneke** [comment]
It's nice to have the first tests finish in under one minute and after few minutes, all tests are completed in 5 minutes. 🥳

**Pull request merged**
