### PR TITLE
Dev/agiltron switch

### PR DESCRIPTION
**Pull request by haighpa**
adds functionality for the agiltron 1xN mems switch

### CODE REVIEW

**Comment by bmoneke** [comment]
Hey @haighpa , thanks for contributing a new instrument to pymeasure. It's a pleasure seeing new people contributing and seeing the instrument database growing.

Did you have a look at the documentation regarding [adding instruments](https://pymeasure.readthedocs.io/en/latest/dev/adding_instruments/index.html)?

If you have questions on how to implement it, don't hesitate to ask.

**Comment by bmoneke** [comment]
@sashagaz thanks for contributing, but please have a look at our code style at pymeasure: https://pymeasure.readthedocs.io/en/latest/dev/adding_instruments/index.html

**Comment by haighpa** [comment]
Hi Benedikt,

We are not intending to push back from our local fork. Apologies for the many notifications you must be getting. Many thanks for all of your work on pymeasure

All the best
Paul

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bmoneke** [comment]
So I may close the pull request?

> We are not intending to push back from our local fork

Open source software lives from sharing code, therefore we'd appreciate it, if you share improvements / new instruments.

**Comment by haighpa** [comment]
Hi Benedikt,

Yes please do.

We know, we have contributed to pymeasure already. What we are doing now is developing tools for a very bespoke setup that also uses proprietary code, so will be more or less useless for the general user and hence not intending to push all the way back

All the best
Paul

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bmoneke** [comment]
Ah I see. You're not pushing code specific to a certain setup.
Thanks for contributing!

**Pull request closed without merging**
