### PR TITLE
Add autodoc warnings to the problem matcher.

### PR DESCRIPTION
**Pull request by bilderbuchi**
This should enable us to at least flag autodoc
import errors in the diff view.
Catching error otherwise is not feasible, see #583.

### CODE REVIEW

**Comment by bilderbuchi** [comment]
Great, I can match the warning, but it does not generate an annotation, but is only visible in the "checks" screen, where nobody notices it:
image
Maybe because it has no file location attached (because there is none) -- that cannot be hardcoded (e.g. to docs/conf.py) afaict

**Comment by bilderbuchi** [comment]
OK, I don't know how to make those annotations appear in the PR diff view, or otherwise notify the user about problems.

@msmttchr  @CasperSchippers should we instead fail the build if we get any warnings in the docs step? That I could accomplish.
So far I did not want to stop the whole CI build just because of linting problems, because we could show those via annotations and not delaying pytest runs accelerates the feedback loop. If this causes us to miss warnings of incomplete docs that is a bit more severe, though.

**Comment by msmttchr** [comment]
I would vote for failing the build

**Comment by bilderbuchi** [comment]
OK, I'm failing the docs job now if we get any warnings, the rest of the workflow continues to run.

**Comment by CasperSchippers** [comment]
I indeed agree on this; if there is no other way to ensure we don't miss issues with the docs, failing the build is the best way to go. Good work.

**Comment by samcondon4** [comment]
Looks like mine was the problem PR. Yeah, I only very recently learned about how the linter reports were working so I had no idea that my commit caused any issues at the time. Good call to fail the build on this so that this doesn't happen again in the future.

**Pull request merged**
